name: Deploy to Windows EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy via SCP
        run: |
          scp -r . ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }}:"${{ secrets.EC2_DEST_PATH }}"

      - name: Start Node App (optional)
        run: |
          ssh ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} \
          "cd ${ secrets.EC2_DEST_PATH } && npm install && npx kill-port 3000 && start /B node app.js"
